/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.UI;

import com.poly.Helper.XImage;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author phong
 */
public class AboutJDialog extends javax.swing.JDialog {

    /**
     * Creates new form About
     */
    public AboutJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
    }
    
    private void goingWebsite(){
        try {
            Desktop.getDesktop().browse(new File("website", "index.html").toURI());
        } catch (IOException ex) {
            Logger.getLogger(AboutJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void goingWebsite1(){
        Desktop link = Desktop.getDesktop();
        try {
            link.browse(new URI("https://www.facebook.com/User.VoQuangThoai"));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWall = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLinkWeb = new javax.swing.JLabel();
        lblLinkWeb1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpGioiThieu = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");

        pnlWall.setBackground(new java.awt.Color(51, 51, 51));

        pnlLogo.setBackground(new java.awt.Color(51, 51, 51));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/Icons/about_logo_tcc_x500.png"))); // NOI18N

        lblLinkWeb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLinkWeb.setForeground(new java.awt.Color(255, 255, 255));
        lblLinkWeb.setText("About us");
        lblLinkWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLinkWebMousePressed(evt);
            }
        });

        lblLinkWeb1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLinkWeb1.setForeground(new java.awt.Color(255, 255, 255));
        lblLinkWeb1.setText("Facebook");
        lblLinkWeb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLinkWeb1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addComponent(lblLinkWeb)
                        .addGap(18, 18, 18)
                        .addComponent(lblLinkWeb1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkWeb)
                    .addComponent(lblLinkWeb1))
                .addGap(18, 18, 18)
                .addComponent(lblLogo)
                .addGap(111, 111, 111))
        );

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PHẦN MỀM QUẢN LÝ QUÁN CAFÉ");

        txpGioiThieu.setEditable(false);
        txpGioiThieu.setBackground(new java.awt.Color(51, 51, 51));
        txpGioiThieu.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        txpGioiThieu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txpGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        txpGioiThieu.setText("== GIỚI THIỆU ==\n  Phần mềm hỗ trợ người dùng quản lý quán café một cách đơn giản. Tạo môi trường làm việc \n  thân thiện cho nhân viên, giúp thanh toán nhanh chóng và lưu trữ hóa đơn.Với các chức năng \n  thanh toán, quản lý bàn, quản lý nhân viên, v.v...   \n\n== YÊU CẦU CÀI ĐẶT ==\n * Hệ điều hành hỗ trợ: Windows 7, 8, 10 \n * Kích thước màn hình: 1600x900 [yêu cầu tối thiểu], 1920x1080 [khuyến nghị cho cảm ứng] \n * Môi trường: JDK 1.8\n * Quản lý data: SQL Server 8 [hoặc cao hơn]\n\n== THÔNG TIN CẬP NHẬT ==\n *[Cập nhật lần cuối - 20:23 - 23/11/2021]\n\n== NHÓM PHÁT TRIỂN DỰ ÁN ==\n *Coder: \n Huỳnh Tấn Phát\n Võ Quang Thoại\n Lê Công Thành\n Lê Thanh Tùng\n Phan Hoài Bảo \n\n * UI: \n Phan Hoài Bảo\n");
        txpGioiThieu.setCaretColor(new java.awt.Color(255, 255, 255));
        txpGioiThieu.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jScrollPane1.setViewportView(txpGioiThieu);

        javax.swing.GroupLayout pnlWallLayout = new javax.swing.GroupLayout(pnlWall);
        pnlWall.setLayout(pnlWallLayout);
        pnlWallLayout.setHorizontalGroup(
            pnlWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlWallLayout.setVerticalGroup(
            pnlWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlWallLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLinkWebMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkWebMousePressed
        this.goingWebsite();
    }//GEN-LAST:event_lblLinkWebMousePressed

    private void lblLinkWeb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkWeb1MousePressed
       goingWebsite1();
    }//GEN-LAST:event_lblLinkWeb1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutJDialog dialog = new AboutJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLinkWeb;
    private javax.swing.JLabel lblLinkWeb1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlWall;
    private javax.swing.JTextPane txpGioiThieu;
    // End of variables declaration//GEN-END:variables
}
