/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.UI;

/**
 *
 * @author phong
 */
public class ThucDonJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThucDonJDialog
     */
    public ThucDonJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWall = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblHeaderBackground = new javax.swing.JLabel();
        pnlMon = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTenMon = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        lblDanhMuc = new javax.swing.JLabel();
        lblAnhMon = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        cboDanhMuc = new javax.swing.JComboBox<>();
        spnDonGia = new com.toedter.components.JSpinField();
        lblMaMon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlControl1 = new javax.swing.JPanel();
        btnNewM = new javax.swing.JButton();
        btnSaveM = new javax.swing.JButton();
        btnUpdateM = new javax.swing.JButton();
        btnDeleteM = new javax.swing.JButton();
        pnlLoaiMon = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstLoaiMon = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiMon = new javax.swing.JTable();
        pnlLoaiMonBox = new javax.swing.JPanel();
        lblMaLoaiMon = new javax.swing.JLabel();
        lblTenLoaiMon = new javax.swing.JLabel();
        txtMaLoaiMon = new javax.swing.JTextField();
        txtTenLoaiMon = new javax.swing.JTextField();
        pnlControl2 = new javax.swing.JPanel();
        btnNewLM = new javax.swing.JButton();
        btnSaveLM = new javax.swing.JButton();
        btnUpdateLM = new javax.swing.JButton();
        btnDeleteLM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        pnlWall.setBackground(new java.awt.Color(255, 255, 255));

        pnlHeader.setPreferredSize(new java.awt.Dimension(1600, 50));
        pnlHeader.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("THỰC ĐƠN");
        pnlHeader.add(lblTitle);
        lblTitle.setBounds(10, 0, 1580, 50);

        lblHeaderBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/Icons/header_black_1920x100.png"))); // NOI18N
        lblHeaderBackground.setToolTipText("");
        pnlHeader.add(lblHeaderBackground);
        lblHeaderBackground.setBounds(0, 0, 1600, 50);

        pnlMon.setBackground(new java.awt.Color(255, 255, 255));
        pnlMon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/Icons/logo-horizontal-black_350x70.png"))); // NOI18N

        lblTenMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenMon.setText("Tên món:");

        lblDonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDonGia.setText("Đơn giá:");

        lblDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDanhMuc.setText("Danh mục:");

        lblAnhMon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhMon.setText("Ảnh");
        lblAnhMon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtMaMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaMon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtTenMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenMon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        cboDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "PHIN Coffee", "Espresso Coffee", "Trà", "Bánh mì", "Bánh ngọt", "Thức uống" }));

        spnDonGia.setBackground(new java.awt.Color(255, 255, 255));
        spnDonGia.setBorder(new javax.swing.border.MatteBorder(null));

        lblMaMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaMon.setText("Mã món:");

        pnlControl1.setBackground(new java.awt.Color(255, 255, 255));
        pnlControl1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        btnNewM.setBackground(new java.awt.Color(255, 255, 255));
        btnNewM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewM.setText("Tạo mới");
        btnNewM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl1.add(btnNewM);

        btnSaveM.setBackground(new java.awt.Color(255, 255, 255));
        btnSaveM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveM.setText("Thêm");
        btnSaveM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl1.add(btnSaveM);

        btnUpdateM.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateM.setText("Sửa");
        btnUpdateM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl1.add(btnUpdateM);

        btnDeleteM.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteM.setText("Xóa");
        btnDeleteM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl1.add(btnDeleteM);

        javax.swing.GroupLayout pnlMonLayout = new javax.swing.GroupLayout(pnlMon);
        pnlMon.setLayout(pnlMonLayout);
        pnlMonLayout.setHorizontalGroup(
            pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlControl1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMonLayout.createSequentialGroup()
                        .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDanhMuc)
                            .addComponent(lblMaMon)
                            .addComponent(lblTenMon)
                            .addComponent(lblDonGia))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spnDonGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenMon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaMon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDanhMuc, 0, 360, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnhMon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        pnlMonLayout.setVerticalGroup(
            pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMonLayout.createSequentialGroup()
                        .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaMon)
                            .addComponent(txtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenMon)
                            .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAnhMon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pnlLoaiMon.setBackground(new java.awt.Color(255, 255, 255));

        lstLoaiMon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOẠI MÓN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        lstLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstLoaiMon.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tất cả", "PHIN Coffee", "Espresso Coffee", "Trà", "Bánh mì", "Bánh ngọt", "Thức uống", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLoaiMon.setAlignmentX(1.0F);
        lstLoaiMon.setAlignmentY(1.0F);
        lstLoaiMon.setFocusable(false);
        jScrollPane3.setViewportView(lstLoaiMon);

        tblLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblLoaiMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã món", "Tên", "Đơn giá", "Mã loại món"
            }
        ));
        jScrollPane1.setViewportView(tblLoaiMon);

        javax.swing.GroupLayout pnlLoaiMonLayout = new javax.swing.GroupLayout(pnlLoaiMon);
        pnlLoaiMon.setLayout(pnlLoaiMonLayout);
        pnlLoaiMonLayout.setHorizontalGroup(
            pnlLoaiMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLoaiMonLayout.setVerticalGroup(
            pnlLoaiMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiMonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoaiMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlLoaiMonBox.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoaiMonBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOẠI MÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblMaLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaLoaiMon.setText("Mã loại món:");

        lblTenLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTenLoaiMon.setText("Tên loại món:");

        txtMaLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaLoaiMon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtTenLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenLoaiMon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        pnlControl2.setBackground(new java.awt.Color(255, 255, 255));
        pnlControl2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 20));

        btnNewLM.setBackground(new java.awt.Color(255, 255, 255));
        btnNewLM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewLM.setText("Tạo mới");
        btnNewLM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl2.add(btnNewLM);

        btnSaveLM.setBackground(new java.awt.Color(255, 255, 255));
        btnSaveLM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSaveLM.setText("Thêm");
        btnSaveLM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl2.add(btnSaveLM);

        btnUpdateLM.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateLM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateLM.setText("Sửa");
        btnUpdateLM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl2.add(btnUpdateLM);

        btnDeleteLM.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteLM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteLM.setText("Xóa");
        btnDeleteLM.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlControl2.add(btnDeleteLM);

        javax.swing.GroupLayout pnlLoaiMonBoxLayout = new javax.swing.GroupLayout(pnlLoaiMonBox);
        pnlLoaiMonBox.setLayout(pnlLoaiMonBoxLayout);
        pnlLoaiMonBoxLayout.setHorizontalGroup(
            pnlLoaiMonBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiMonBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoaiMonBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoaiMonBoxLayout.createSequentialGroup()
                        .addGroup(pnlLoaiMonBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenLoaiMon)
                            .addComponent(lblMaLoaiMon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLoaiMonBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLoaiMon)
                            .addComponent(txtTenLoaiMon)))
                    .addComponent(pnlControl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLoaiMonBoxLayout.setVerticalGroup(
            pnlLoaiMonBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiMonBoxLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlLoaiMonBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaLoaiMon)
                    .addComponent(txtMaLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlLoaiMonBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTenLoaiMon)
                    .addComponent(txtTenLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(pnlControl2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlWallLayout = new javax.swing.GroupLayout(pnlWall);
        pnlWall.setLayout(pnlWallLayout);
        pnlWallLayout.setHorizontalGroup(
            pnlWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlWallLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLoaiMonBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlLoaiMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlWallLayout.setVerticalGroup(
            pnlWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWallLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlWallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLoaiMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlWallLayout.createSequentialGroup()
                        .addComponent(pnlMon, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlLoaiMonBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThucDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThucDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThucDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThucDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThucDonJDialog dialog = new ThucDonJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteLM;
    private javax.swing.JButton btnDeleteM;
    private javax.swing.JButton btnNewLM;
    private javax.swing.JButton btnNewM;
    private javax.swing.JButton btnSaveLM;
    private javax.swing.JButton btnSaveM;
    private javax.swing.JButton btnUpdateLM;
    private javax.swing.JButton btnUpdateM;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAnhMon;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblHeaderBackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMaLoaiMon;
    private javax.swing.JLabel lblMaMon;
    private javax.swing.JLabel lblTenLoaiMon;
    private javax.swing.JLabel lblTenMon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstLoaiMon;
    private javax.swing.JPanel pnlControl1;
    private javax.swing.JPanel pnlControl2;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLoaiMon;
    private javax.swing.JPanel pnlLoaiMonBox;
    private javax.swing.JPanel pnlMon;
    private javax.swing.JPanel pnlWall;
    private com.toedter.components.JSpinField spnDonGia;
    private javax.swing.JTable tblLoaiMon;
    private javax.swing.JTextField txtMaLoaiMon;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtTenLoaiMon;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
